{% set name = "storage3" %}
{% set version = "2.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c8231f2c1090f3ef164cbd2c66917f92b112ec0da45cf3151f2dea314861b9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.8.3,<0.9.0
  run:
    - python >={{ python_min }}
    - httpx >=0.26.0,<0.29
    - typing-extensions >=4.2.0
    - deprecation >=2.1.0
    - pydantic >=2.11.7,<3

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - storage3

about:
  home: https://github.com/supabase/supabase-py/tree/main/src/storage
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client library to interact with Supabase Storage
  description: Python Client library to interact with Supabase Storage

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
