{% set name = "storage3" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32ea8f5eb2f7185c2114a4f6ae66d577722e32503f0a30b56e7ed5c7f13e6b48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - httpx >=0.26.0,<0.28
    - typing-extensions >=4.2.0
    - python-dateutil >=2.8.2
    - deprecation >=2.1.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - storage3

about:
  home: https://github.com/supabase-community/storage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client library to interact with Supabase Storage
  description: |
    Python Client library to interact with Supabase Storage

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
