{% set name = "storage3" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 243583f2180686c0f0a19e6117d8a9796fd60c0ca72ec567d62b75a5af0d57a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - httpx >=0.26.0,<0.28
    - typing-extensions >=4.2.0
    - python-dateutil >=2.8.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - storage3

about:
  home: https://github.com/supabase-community/storage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client library to interact with Supabase Storage
  description: |
    Python Client library to interact with Supabase Storage

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
